-- Update tinggi_badan and beratbadan for 25 random mothers
UPDATE ibu SET tinggi_badan = 155.5, beratbadan = 52 WHERE id = 1;
UPDATE ibu SET tinggi_badan = 162.0, beratbadan = 58 WHERE id = 3;
UPDATE ibu SET tinggi_badan = 158.5, beratbadan = 55 WHERE id = 5;
UPDATE ibu SET tinggi_badan = 160.0, beratbadan = 60 WHERE id = 7;
UPDATE ibu SET tinggi_badan = 157.0, beratbadan = 53 WHERE id = 9;
UPDATE ibu SET tinggi_badan = 163.5, beratbadan = 62 WHERE id = 11;
UPDATE ibu SET tinggi_badan = 159.0, beratbadan = 57 WHERE id = 13;
UPDATE ibu SET tinggi_badan = 156.5, beratbadan = 54 WHERE id = 15;
UPDATE ibu SET tinggi_badan = 161.0, beratbadan = 59 WHERE id = 17;
UPDATE ibu SET tinggi_badan = 154.0, beratbadan = 51 WHERE id = 19;
UPDATE ibu SET tinggi_badan = 165.0, beratbadan = 65 WHERE id = 21;
UPDATE ibu SET tinggi_badan = 158.0, beratbadan = 56 WHERE id = 23;
UPDATE ibu SET tinggi_badan = 160.5, beratbadan = 61 WHERE id = 25;
UPDATE ibu SET tinggi_badan = 157.5, beratbadan = 54 WHERE id = 27;
UPDATE ibu SET tinggi_badan = 162.5, beratbadan = 63 WHERE id = 29;
UPDATE ibu SET tinggi_badan = 159.5, beratbadan = 58 WHERE id = 31;
UPDATE ibu SET tinggi_badan = 156.0, beratbadan = 52 WHERE id = 33;
UPDATE ibu SET tinggi_badan = 164.0, beratbadan = 64 WHERE id = 35;
UPDATE ibu SET tinggi_badan = 158.5, beratbadan = 57 WHERE id = 37;
UPDATE ibu SET tinggi_badan = 161.5, beratbadan = 60 WHERE id = 39;
UPDATE ibu SET tinggi_badan = 155.0, beratbadan = 50 WHERE id = 41;
UPDATE ibu SET tinggi_badan = 163.0, beratbadan = 62 WHERE id = 43;
UPDATE ibu SET tinggi_badan = 159.0, beratbadan = 56 WHERE id = 45;
UPDATE ibu SET tinggi_badan = 157.0, beratbadan = 55 WHERE id = 47;
UPDATE ibu SET tinggi_badan = 160.0, beratbadan = 59 WHERE id = 49;

-- Update isPerokok status for 25 random husbands
UPDATE suami SET isPerokok = 1 WHERE id = 2;
UPDATE suami SET isPerokok = 1 WHERE id = 4;
UPDATE suami SET isPerokok = 0 WHERE id = 6;
UPDATE suami SET isPerokok = 1 WHERE id = 8;
UPDATE suami SET isPerokok = 0 WHERE id = 10;
UPDATE suami SET isPerokok = 1 WHERE id = 12;
UPDATE suami SET isPerokok = 0 WHERE id = 14;
UPDATE suami SET isPerokok = 1 WHERE id = 16;
UPDATE suami SET isPerokok = 1 WHERE id = 18;
UPDATE suami SET isPerokok = 0 WHERE id = 20;
UPDATE suami SET isPerokok = 1 WHERE id = 22;
UPDATE suami SET isPerokok = 0 WHERE id = 24;
UPDATE suami SET isPerokok = 1 WHERE id = 26;
UPDATE suami SET isPerokok = 1 WHERE id = 28;
UPDATE suami SET isPerokok = 0 WHERE id = 30;
UPDATE suami SET isPerokok = 1 WHERE id = 32;
UPDATE suami SET isPerokok = 0 WHERE id = 34;
UPDATE suami SET isPerokok = 1 WHERE id = 36;
UPDATE suami SET isPerokok = 1 WHERE id = 38;
UPDATE suami SET isPerokok = 0 WHERE id = 40;
UPDATE suami SET isPerokok = 1 WHERE id = 42;
UPDATE suami SET isPerokok = 0 WHERE id = 1;
UPDATE suami SET isPerokok = 1 WHERE id = 3;
UPDATE suami SET isPerokok = 0 WHERE id = 5;
UPDATE suami SET isPerokok = 1 WHERE id = 7;